app = "rms-upload"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "Dockerfile"

[env]
  PORT = "8501"

[[services]]
  internal_port = 8501
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 80
